"""
Django settings for mwami project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url
from datetime import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!#
# SECURITY SETTINGS
SECRET_KEY = config('DJANGO_SECRET_KEY')
DEBUG = config('MY_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('MY_ALLOWED_HOSTS', default='127.0.0.1', cast=lambda v: v.split(','))


CSRF_TRUSTED_ORIGINS = config('MY_CSRF_TRUSTED_ORIGINS', cast=lambda v: v.split(','))

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
    'channels',
    'dashboard.apps.DashboardConfig',
    'django_apscheduler',
    "django_browser_reload",
    'social_django',
    'ckeditor',
    'widget_tweaks',
]

JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "Kigali Driving School Admin",
    "site_header": "Kigali Driving School",
    "site_brand": "KDS Admin",
    "site_logo": "img/logo.png",
    "site_logo_classes": "img-circle",
    "site_logo_small": "img/logo.png",
    "site_icon": "img/favicon.ico",
    "welcome_sign": f"Welcome to Kigali Driving School Admin | {datetime.now().year}",
    "copyright": f"Kigali Driving School",
    
    # Search
    "search_model": [
        "app.UserProfile",
        "app.Subscription", 
        "app.Exam", 
        "app.Question"
    ],

    # UI
    "show_sidebar": True,
    "navigation_expanded": False,
    "order_with_respect_to": ["app.UserProfile", "app.Subscription", ],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    "theme": "darkly",  # Always use dark theme
    "dark_mode_theme": "darkly",  # Ensure dark mode uses same theme
    "theme_toggle": False,  # Disable switching to light theme

    
    # Customization
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        
    ],
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# SESSION SETTINGS
SESSION_COOKIE_AGE = 60*60*24*30 # 30 days

SESSION_SAVE_EVERY_REQUEST = config('SESSION_SAVE_EVERY_REQUEST', default=True, cast=bool)


AUTH_USER_MODEL = 'app.UserProfile'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'app.middleware.AdminAccessMiddleware',
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'mwami.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.exams_slider_context',
                'app.context_processors.unverified_subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mwami.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
LOCAL_DB = config('LOCAL_DB', default=False, cast=bool)
if LOCAL_DB == True:
   DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'clement',
        'USER': 'root',
        'PASSWORD': 'ememai',
        'HOST': '127.0.0.1',  # Or 'localhost'
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

else:
    DATABASES = {
        'default': dj_database_url.config(default=config('DB_URL'))
    }

AUTHENTICATION_BACKENDS = [
    'app.authentication.EmailOrPhoneBackend',  # Custom email/phone backend
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',   # Default Django backend
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kigali'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

#for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
    ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

BASE_URL = config("BASE_URL",)

# Email for production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# MTN MOMO API CONFIGURATION
MTN_MOMO_SUBSCRIPTION_KEY = config("MTN_MOMO_SUBSCRIPTION_KEY")
MTN_MOMO_API_USER_ID = config("MTN_MOMO_API_USER_ID")
MTN_MOMO_API_KEY = config("MTN_MOMO_API_KEY")
MTN_MOMO_CALLBACK_URL = config("MTN_MOMO_CALLBACK_URL")
MTN_MOMO_COLLECTION_PRIMARY_KEY = config("MTN_MOMO_COLLECTION_PRIMARY_KEY")
MTN_MOMO_BASE_URL = config("MTN_MOMO_BASE_URL")

LOGIN_URL = 'login'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_CLIENT_SECRET')

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'app.users.pipeline.associate_by_email',  # 👈 Corrected import path
    'app.users.pipeline.save_user_names',     # 👈 Corrected import path
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)


# Set a value for SECURE_HSTS_SECONDS
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)

# Enable HTTP Strict Transport Security
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)

# Redirect all HTTP connections to HTTPS
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)

# Use secure-only session cookies
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)

# Use secure-only CSRF cookies
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)

# settings.py
CSRF_FAILURE_VIEW = 'app.views.csrf_failure'

WHATSAPP_API_URL = config('WHATSAPP_API_URL', default='https://7107.api.green-api.com')
INSTANCE_ID = config('INSTANCE_ID', default='7107355142')
API_TOKEN = config('API_TOKEN', default='b8eac2c56f16425287ff5a08813f7fe4d1436b1dbfc54aa091')

ADMIN_PHONE_NUMBER = config('ADMIN_PHONE_NUMBER',)