# Generated by Django 5.1.6 on 2025-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end_date',
        ),
        migrations.AlterField(
            model_name='userexam',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
