# Generated by Django 5.1.6 on 2025-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
