# Generated by Django 5.1.6 on 2025-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
