# Generated by Django 5.1.6 on 2025-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_examtype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ManyToManyField(default='Ibivanze', null=True, to='app.examtype', verbose_name='Question Type'),
        ),
    ]
