# Generated by Django 5.1.6 on 2025-04-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default='Ibivanze', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examtype', verbose_name='Question Type'),
        ),
    ]
